### PR TITLE
Ubuntu support

### PR DESCRIPTION
**Pull request by danbst**
I've been using it on Ubuntu for a few month, hence I'm adding all the necessary steps.

- make `mutableServicesDir` dependent on operating system. My heuristic is that only NixOS defines this different, and most others distributions use `/etc/systemd-mutable/system` as a default. This is the case for Ubuntu at least
- create `/etc/static/os-release` to sidestep problem https://github.com/NixOS/nixpkgs/issues/28833. This should be harmless, but this is definitely a hack. If smbd starts a container and then removes `/etc/static/os-release`, container will fail on restart. But `extra-container create -s -r` should fix that. I'd say, this is fine untils smbd fixes root issue at NixOS
- rewrite package from `builderScript` to regular derivation, to propagate `nixos-container`. Just to make dep clear
- replace `nixos-container` calls with `${nixos-container}/bin/nixos-container` during build. Because this is how it should be :)
- installation docs. Tested on Ubuntu 18.04
- some minor tweeks (like .gitignore and missing argument in `extra-container create` doc)

### CODE REVIEW

**Comment by danbst** [comment]
@erikarvstedt ready for review

**Comment by danbst** [comment]
ping @erikarvstedt

**Comment by erikarvstedt** [comment]
Thanks a lot, and sorry for letting you wait. :disappointed_relieved:

I've added a few fixes in branch [ubuntu-support-ea](https://github.com/erikarvstedt/extra-container/commits/ubuntu-support-ea).

- I've restored the use of `buildCommand` as it's much simpler: [diff](https://github.com/erikarvstedt/extra-container/compare/142afc3fba9b33b3b7d4951459a31b529bc1ca29...2c7b6be1ca6ede21d545fa3caa54ac57b38ed1ac#diff-5712e736e0de6ba170577f8472c398e9).
- Could you please add a comment in the source to explain the `/etc/static/os-release` hack? Where and why is it needed? On NixOS or Ubuntu? What has `smbd` (samba) to do with this?
- Could you prepare a script for testing Ubuntu support on NixOS? The script should do roughly the following:
  - Create a non-graphical QEMU Ubuntu or Debian VM (maybe use `<nixpkgs/pkgs/build-support/vm/default.nix>`).
  - Start the VM and run the test suite.
- Not strictly needed, but it would be great if you could do that: Fix the [WIP Travis test script](https://github.com/erikarvstedt/extra-container/blob/ubuntu-support-ea/.travis.yml).
  It [currently fails](https://travis-ci.org/erikarvstedt/extra-container/builds/654854788) with:
  ```
   Failed to register machine: The name org.freedesktop.machine1 was not provided by any .service files
   ```

**Comment by erikarvstedt** [comment]
Also, could you rebase? This gets us the lastest perf improvements.

**Comment by danbst** [comment]
yup, will do

**Comment by danbst** [comment]
> Could you please add a comment in the source to explain the /etc/static/os-release hack? 

I think this can be fixed in NixOS, but it only happens in containers on non-NixOS.

We have to change https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/virtualisation/containers.nix#L75 to `touch "$root/etc/os-release" || true` and wait new NixOS release. Then this hack will no longer be required (I hope).

**Comment by erikarvstedt** [comment]
Release `0.5` includes generic systemd support. Thanks for the proposal and the initial implementation!

**Comment by tgunnoe** [comment]
This... sounds awesome. Good job!

**Pull request closed without merging**
